services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: musculmania_user
      POSTGRES_PASSWORD: musculmania_pass
      POSTGRES_DB: musculmania_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
