services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Mantén el comando en 'sleep infinity' para que el contenedor no se cierre
    command: sleep infinity

    # Puedes utilizar network_mode si necesitas que se comunique con el servicio "db"
    network_mode: service:db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gitpod
      POSTGRES_DB: musculmania_db
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres-data:

